ProtocolGovernance spec test
mellow-finance/mellow-vaults pull request #104
Opened 2022-02-04 23:45 UTC by AlexSaplin

2022-02-05 17:02 UTC, alexeuler requested changes

2022-02-05 17:02 UTC, alexeuler commented on test/ProtocolGovernance.spec.ts
> +                pit(
Let's not use pit in access control, it will give bad spec view. Just do one case with random address

2022-02-08 08:13 UTC, AlexSaplin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Protocol Governance tests](https://trello.com/c/j2Ui6tFR/317-protocol-governance-tests)

2022-02-10 10:16 UTC, alexeuler approved these changes

2022-02-14 07:06 UTC, merged