Added hooks for deposit
mellow-finance/mellow-vaults pull request #122
Opened 2022-03-30 18:46 UTC by AlexSaplin

2022-04-01 07:48 UTC, alexeuler requested changes

2022-04-01 07:48 UTC, alexeuler commented on contracts/vaults/ERC20RootVault.sol
> +    bytes4 public constant REBALANCE_SELECTOR = 0xe78eeb6d;
Let's make it more explicit
+ I would name it depositCallback + withdrawCallback

2022-04-01 07:48 UTC, alexeuler commented on contracts/vaults/ERC20RootVault.sol
> +        bytes memory callbackOptions
It should not be user inputs

2022-04-01 07:48 UTC, alexeuler commented on contracts/vaults/ERC20RootVault.sol
> +        bytes memory callbackOptions
The callback address should be delayedStrategyParams parameter

2022-04-07 09:49 UTC, alexeuler approved these changes

2022-04-08 08:44 UTC, grigorevPavel approved these changes

2022-04-08 18:34 UTC, closed without merging